services:
  - type: web
    name: dzdeal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: dzdeal_db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        value: https://vpbecafeatykzyufzuhp.supabase.co
      - key: DEBUG
        value: false

databases:
  - name: dzdeal_db
    databaseName: dzdeal
    user: dzdeal
    plan: free
