services:
  - type: web
    name: dzdeal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: PYTHONPATH
        value: .
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        value: https://vpbecafeatykzyufzuhp.supabase.co
      - key: DEBUG
        value: "false"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_HOST
        value: db.vpbecafeatykzyufzuhp.supabase.co
      - key: DB_PORT
        value: "5432"

databases:
  - name: dzdeal_db
    databaseName: dzdeal
    user: dzdeal
    plan: free
